version: '3.1'

services:

  db:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/test.sql:/docker-entrypoint-initdb.d/test.sql
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
  server:
    build: server/
    restart: always
    ports:
      - "8081:8081"
    links:
      - db
  client:
    build: client/
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - server
  
volumes:
  pgadmin-data: